### ISSUE TITLE
Missing preprocessor_config.json in Weights Folder

### ISSUE THREAD

**Issue by fubostudy** [farewellthree/PPLLaVA#2]
**Description:**
Attempting to run `demo.py` with the following command results in an error:

```shell
CUDA_VISIBLE_DEVICES=0 python3 demo.py --ckpt-path weights/ppllava_weight/ppllava_vicuna7b_image_video
```

**Error Traceback:**
```
Traceback (most recent call last):
  File "/root/PPLLaVA/demo.py", line 84, in <module>
    processor = LLaVA_Processer(model_config)
  File "/root/PPLLaVA/ppllava/test/video_utils.py", line 278, in __init__
    self.processor = process_cls.from_pretrained(llama_model)
  ...
OSError: weights/ppllava_weight/ppllava_vicuna7b_image_video does not appear to have a file named preprocessor_config.json. 
```

**Current Contents of `weights/ppllava_weight/ppllava_vicuna7b_image_video`:**
```
config.json
generation_config.json
model-00001-of-00003.safetensors
model-00002-of-00003.safetensors
model-00003-of-00003.safetensors
model.safetensors.index.json
tokenizer_config.json
tokenizer.json
tokenizer.model
trainer_state.json
training_args.bin
```

**Steps to Reproduce:**
1. Execute the command as shown above in the `PPLLaVA` environment.
2. Observe the missing `preprocessor_config.json` file error.

**Expected Behavior:**
The script should locate `preprocessor_config.json` or have a fallback process if this file is missing.

**Suggested Resolution:**
- Please provide the missing `preprocessor_config.json` file or update documentation on alternatives.

----

```shell
(ppllava) (base) root@ubuntu22:~/PPLLaVA# CUDA_VISIBLE_DEVICES=0 python3 demo.py --ckpt-path weights/ppllava_weight/ppllava_vicuna7b_image_video
11/08 13:21:18 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
11/08 13:21:18 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
[2024-11-08 13:21:25,907] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Initializing Chat
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:20<00:00, 26.85s/it]
Traceback (most recent call last):
  File "/root/PPLLaVA/demo.py", line 84, in <module>
    processor = LLaVA_Processer(model_config)
  File "/root/PPLLaVA/ppllava/test/video_utils.py", line 278, in __init__
    self.processor = process_cls.from_pretrained(llama_model)
  File "/home/vipuser/miniconda3/envs/ppllava/lib/python3.9/site-packages/transformers/processing_utils.py", line 915, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/root/PPLLaVA/ppllava/datasets/datasets/llavavid_processor.py", line 235, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "/home/vipuser/miniconda3/envs/ppllava/lib/python3.9/site-packages/transformers/image_processing_base.py", line 206, in from_pretrained
    image_processor_dict, kwargs = cls.get_image_processor_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/vipuser/miniconda3/envs/ppllava/lib/python3.9/site-packages/transformers/image_processing_base.py", line 335, in get_image_processor_dict
    resolved_image_processor_file = cached_file(
  File "/home/vipuser/miniconda3/envs/ppllava/lib/python3.9/site-packages/transformers/utils/hub.py", line 374, in cached_file
    raise EnvironmentError(
OSError: weights/ppllava_weight/ppllava_vicuna7b_image_video does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/weights/ppllava_weight/ppllava_vicuna7b_image_video/tree/main' for available files.
(ppllava) (base) root@ubuntu22:~/PPLLaVA# ll weights/ppllava_weight/ppllava_vicuna7b_image_video
总计 14181580
drwxr-xr-x 2 root root       4096 11月  8 11:45 ./
drwxr-xr-x 7 root root       4096 11月  8 11:55 ../
-rwxr-xr-x 1 root root       1758 11月  8 11:10 config.json*
-rwxr-xr-x 1 root root        132 11月  8 11:10 generation_config.json*
-rwxr-xr-x 1 root root 4980641554 11月  8 11:38 model-00001-of-00003.safetensors*
-rwxr-xr-x 1 root root 4957878536 11月  8 11:37 model-00002-of-00003.safetensors*
-rwxr-xr-x 1 root root 4580905400 11月  8 11:45 model-00003-of-00003.safetensors*
-rwxr-xr-x 1 root root     106381 11月  8 11:10 model.safetensors.index.json*
-rwxr-xr-x 1 root root       1180 11月  8 11:10 tokenizer_config.json*
-rwxr-xr-x 1 root root    1843105 11月  8 11:10 tokenizer.json*
-rwxr-xr-x 1 root root     499723 11月  8 11:10 tokenizer.model*
-rwxr-xr-x 1 root root      12047 11月  8 11:10 trainer_state.json*
-rwxr-xr-x 1 root root       7032 11月  8 11:10 training_args.bin*
(ppllava) (base) root@ubuntu22:~/PPLLaVA# 
```

**Comment by farewellthree** [comment]
Hi, we recommend using the dpo checkpoint for chatting which contains the preprocessor_config.json
